version: "3.8"

services:
  server:
    build: 
      context: .
      dockerfile: docker/server/Dockerfile.dev
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - ./docker:/app/docker
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - django-auth-api
    restart: unless-stopped
    command: ./docker/server/run.dev.sh

  postgres:
    image: postgres:14.2-alpine3.15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=django-auth-api
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - django-auth-api
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    networks:
      - django-auth-api
    restart: unless-stopped



networks:
  django-auth-api:
    driver: bridge


volumes:
  pg-data:
    driver: local
  pg-admin:
    driver: local